name: banner_listtile
description: Create a tile with banner at the corner and lot more option to customize. Banner with "New" tag or something you want.
version: 2.2.2
homepage: https://github.com/SM-SHIFAT/banner_listtile.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

